SERVER:
  HOST: '127.0.0.1'
  PORT: 37000

RAY:
  CLUSTER_PORT: 30037
  LAUNCH_CLUSTER: True

MANAGER:
  DISABLE_FIXED_NODE_INIT_INSTANCE: False
  DISABLE_INIT_INSTANCE_BY_MANAGER: False

  INITIAL_INSTANCES: 1

  LOAD_METRIC: 'remaining_steps'
  DISPATCH_POLICY: 'load'

  ENABLE_DEFRAG: True

  ENABLE_MIGRATION: True
  REQUEST_MIGRATION_POLICY: 'SJF'

  MIGRATION_BACKEND: 'rpc'
  MIGRATION_CACHE_BLOCKS: 512

  ENABLE_SCALING: False
