SERVER:
  HOST: '127.0.0.1'
  PORT: 1234
  QUEUE_TYPE: "rayqueue"
  RAY_CLUSTER_PORT: 6379
  LAUNCH_RAY_CLUSTER: True

MANAGER:
  DISABLE_FIXED_NODE_INIT_INSTANCE: False
  DISABLE_INIT_INSTANCE_BY_MANAGER: False

  INITIAL_INSTANCES: 1

  LOAD_METRIC: 'remaining_steps'
  DISPATCH_POLICY: 'load'

  ENABLE_MIGRATION: True
  ENABLE_DEFRAG: True
  REQUEST_MIGRATION_POLICY: 'SJF'

  MIGRATION_BACKEND: 'gloo'
  MIGRATION_BUFFER_BLOCKS: 512
  MIGRATION_INTERNAL_BUFFER_NUM: 2

  ENABLE_SCALING: False
