SERVER:
  RAY_CLUSTER_PORT: 6379
  LAUNCH_RAY_CLUSTER: False
  QUEUE_TYPE: "rayqueue"
  

MANAGER:
  DISABLE_FIXED_NODE_INIT_INSTANCE: False
  DISABLE_INIT_INSTANCE_BY_MANAGER: True

  LOAD_METRIC: 'remaining_steps'
  DISPATCH_POLICY: 'load'

  ENABLE_MIGRATION: False
  ENABLE_DEFRAG: True
  REQUEST_MIGRATION_POLICY: 'SJF'

  MIGRATION_BACKEND: 'grpc'
  MIGRATION_CACHE_BLOCKS: 512

  ENABLE_SCALING: False

  LOG_INSTANCE_INFO: True
