SERVER:
  HOST: '127.0.0.1'
  PORT: 1234
  REQUEST_OUTPUT_QUEUE_TYPE: "rayqueue"
  RAY_CLUSTER_PORT: 6379
  LAUNCH_RAY_CLUSTER: True

MANAGER:
  DISABLE_FIXED_NODE_INIT_INSTANCE: False
  DISABLE_INIT_INSTANCE_BY_MANAGER: False

  INITIAL_INSTANCES: 1

  LOAD_METRIC: 'remaining_steps'
  DISPATCH_POLICY: 'load'

  ENABLE_MIGRATION: True
  ENABLE_DEFRAG: True
  REQUEST_MIGRATION_POLICY: 'SR'

  MIGRATION_BACKEND: 'rayrpc'
  MIGRATION_BUFFER_BLOCKS: 512

  ENABLE_SCALING: False
