# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: llumnix/backends/bladellm/proto/llumnix_bladellm.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='llumnix/backends/bladellm/proto/llumnix_bladellm.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n6llumnix/backends/bladellm/proto/llumnix_bladellm.proto\x1a\x1bgoogle/protobuf/empty.proto\"8\n\x0eMigrateRequest\x12\x12\n\nsrc_blocks\x18\x01 \x03(\x05\x12\x12\n\ndst_blocks\x18\x02 \x03(\x05\"2\n\x0c\x41llocRequest\x12\"\n\x1anum_migration_cache_blocks\x18\x01 \x01(\x05\"\x1d\n\x0bSendRequest\x12\x0e\n\x06\x62locks\x18\x01 \x03(\x05\"C\n\x11SendNumpyResponse\x12\x15\n\rdummy_key_cpu\x18\x01 \x03(\x0c\x12\x17\n\x0f\x64ummy_value_cpu\x18\x02 \x03(\x0c\x32\xcf\x01\n\rLlumnixWorker\x12\x43\n\x16migrate_gpu_cache_grpc\x12\x0f.MigrateRequest\x1a\x16.google.protobuf.Empty\"\x00\x12\x43\n\x18\x61llocate_migration_cache\x12\r.AllocRequest\x1a\x16.google.protobuf.Empty\"\x00\x12\x34\n\x0esend_cpu_cache\x12\x0c.SendRequest\x1a\x12.SendNumpyResponse\"\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_MIGRATEREQUEST = _descriptor.Descriptor(
  name='MigrateRequest',
  full_name='MigrateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='src_blocks', full_name='MigrateRequest.src_blocks', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dst_blocks', full_name='MigrateRequest.dst_blocks', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=143,
)


_ALLOCREQUEST = _descriptor.Descriptor(
  name='AllocRequest',
  full_name='AllocRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='num_migration_cache_blocks', full_name='AllocRequest.num_migration_cache_blocks', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=145,
  serialized_end=195,
)


_SENDREQUEST = _descriptor.Descriptor(
  name='SendRequest',
  full_name='SendRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='blocks', full_name='SendRequest.blocks', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=197,
  serialized_end=226,
)


_SENDNUMPYRESPONSE = _descriptor.Descriptor(
  name='SendNumpyResponse',
  full_name='SendNumpyResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='dummy_key_cpu', full_name='SendNumpyResponse.dummy_key_cpu', index=0,
      number=1, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dummy_value_cpu', full_name='SendNumpyResponse.dummy_value_cpu', index=1,
      number=2, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=228,
  serialized_end=295,
)

DESCRIPTOR.message_types_by_name['MigrateRequest'] = _MIGRATEREQUEST
DESCRIPTOR.message_types_by_name['AllocRequest'] = _ALLOCREQUEST
DESCRIPTOR.message_types_by_name['SendRequest'] = _SENDREQUEST
DESCRIPTOR.message_types_by_name['SendNumpyResponse'] = _SENDNUMPYRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MigrateRequest = _reflection.GeneratedProtocolMessageType('MigrateRequest', (_message.Message,), {
  'DESCRIPTOR' : _MIGRATEREQUEST,
  '__module__' : 'llumnix.backends.bladellm.proto.llumnix_bladellm_pb2'
  # @@protoc_insertion_point(class_scope:MigrateRequest)
  })
_sym_db.RegisterMessage(MigrateRequest)

AllocRequest = _reflection.GeneratedProtocolMessageType('AllocRequest', (_message.Message,), {
  'DESCRIPTOR' : _ALLOCREQUEST,
  '__module__' : 'llumnix.backends.bladellm.proto.llumnix_bladellm_pb2'
  # @@protoc_insertion_point(class_scope:AllocRequest)
  })
_sym_db.RegisterMessage(AllocRequest)

SendRequest = _reflection.GeneratedProtocolMessageType('SendRequest', (_message.Message,), {
  'DESCRIPTOR' : _SENDREQUEST,
  '__module__' : 'llumnix.backends.bladellm.proto.llumnix_bladellm_pb2'
  # @@protoc_insertion_point(class_scope:SendRequest)
  })
_sym_db.RegisterMessage(SendRequest)

SendNumpyResponse = _reflection.GeneratedProtocolMessageType('SendNumpyResponse', (_message.Message,), {
  'DESCRIPTOR' : _SENDNUMPYRESPONSE,
  '__module__' : 'llumnix.backends.bladellm.proto.llumnix_bladellm_pb2'
  # @@protoc_insertion_point(class_scope:SendNumpyResponse)
  })
_sym_db.RegisterMessage(SendNumpyResponse)



_LLUMNIXWORKER = _descriptor.ServiceDescriptor(
  name='LlumnixWorker',
  full_name='LlumnixWorker',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=298,
  serialized_end=505,
  methods=[
  _descriptor.MethodDescriptor(
    name='migrate_gpu_cache_grpc',
    full_name='LlumnixWorker.migrate_gpu_cache_grpc',
    index=0,
    containing_service=None,
    input_type=_MIGRATEREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='allocate_migration_cache',
    full_name='LlumnixWorker.allocate_migration_cache',
    index=1,
    containing_service=None,
    input_type=_ALLOCREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='send_cpu_cache',
    full_name='LlumnixWorker.send_cpu_cache',
    index=2,
    containing_service=None,
    input_type=_SENDREQUEST,
    output_type=_SENDNUMPYRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_LLUMNIXWORKER)

DESCRIPTOR.services_by_name['LlumnixWorker'] = _LLUMNIXWORKER

# @@protoc_insertion_point(module_scope)
