FROM nvcr.io/nvidia/pytorch:23.10-py3

ARG BRANCH="main"

RUN curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor >bazel-archive-keyring.gpg && \
    mv bazel-archive-keyring.gpg /usr/share/keyrings && \
    echo "deb [arch=amd64 signed-by=/usr/share/keyrings/bazel-archive-keyring.gpg] https://storage.googleapis.com/bazel-apt stable jdk1.8" | tee /etc/apt/sources.list.d/bazel.list && \
    apt update && apt install bazel-5.1.0 -y && \
    ln -s /usr/bin/bazel-5.1.0 /usr/bin/bazel && \
    apt-get clean

RUN mkdir -p /intall_workspace/llumnix && \
    cd /intall_workspace/llumnix && \
    git clone https://github.com/AlibabaPAI/llumnix.git . && \
    git fetch origin ${BRANCH} && \
    git checkout ${BRANCH} && \
    make pygloo && \
    make check_pylint_installed && \
    make check_pytest_installed && \
    make vllm_install

RUN rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
