FROM blade-llm:local-latest

ARG BRANCH="main"

RUN apt update && apt install -y pciutils && apt clean

RUN wget -qO - http://mirrors.cloud.aliyuncs.com/erdma/GPGKEY | gpg --dearmour -o /etc/apt/trusted.gpg.d/erdma.gpg && \
    echo "deb [ ] http://mirrors.cloud.aliyuncs.com/erdma/apt/ubuntu jammy/erdma main" | tee /etc/apt/sources.list.d/erdma.list && \
    apt update && \
    apt install -y libibverbs1 ibverbs-providers ibverbs-utils librdmacm1 && \
    apt clean

RUN mkdir -p /intall_workspace/llumnix && \
    cd /intall_workspace/llumnix && \
    git clone https://github.com/AlibabaPAI/llumnix.git . && \
    git fetch origin ${BRANCH} && \
    git checkout ${BRANCH} && \
    make check_pylint_installed && \
    make check_pytest_installed && \
    make bladellm_install

RUN mkdir -p /tmp/llumnix/naming
