name: offline_inference

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:
  cancel_previous_workflows:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
    - uses: styfle/cancel-workflow-action@0.12.1
      with:
        all_but_latest: true

  offline_inference:
    needs: cancel_previous_workflows
    runs-on: [self-hosted]
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - name: Run offline inference example
      run: ./tools/run_test.sh offline_test
