name: pylint

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:
  cancel_previous_workflows:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
    - uses: styfle/cancel-workflow-action@0.12.1
      with:
        all_but_latest: true

  pylint_test:
    needs: cancel_previous_workflows
    runs-on: [self-hosted]
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - name: Analysing the code with pylint
      run: |
        nvidia-docker run --rm -t --net host --ipc host \
          -v ${PWD}:/workspace \
          -w /workspace \
          registry.cn-beijing.aliyuncs.com/llumnix/llumnix-bladellm-dev:202506261954_rebase_bladellm_0624_6efc1e8 \
          sh -c "make lint"
