name: unit_test

on:
  workflow_run:
    workflows: ["pylint"]
    types:
      - completed

jobs:
  cancel_previous_workflows:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
    - uses: styfle/cancel-workflow-action@0.12.1
      with:
        all_but_latest: true

  unit_tests:
    needs: cancel_previous_workflows
    runs-on: [self-hosted]
    timeout-minutes: 60
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Kill Running Containers
      run: |
        [[ -n $(docker ps -q) ]] && docker kill $(docker ps -q) || echo "No running containers to kill."
    - name: Build And Test
      run: ./tools/unit_test.sh
