name: unit_test

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  cancel_previous_workflows:
    runs-on: [self-hosted]
    timeout-minutes: 3
    steps:
    - uses: styfle/cancel-workflow-action@0.12.1
      with:
        all_but_latest: true

  unit_tests:
    needs: cancel_previous_workflows
    runs-on: [self-hosted]
    timeout-minutes: 60
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Kill Running Containers
      run: |
        [[ -n $(docker ps -q) ]] && docker kill $(docker ps -q) || echo "No running containers to kill."
    - name: Build And Test
      run: ./tools/unit_test.sh
