name: unit_test

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:
  cancel_previous_workflows:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
    - uses: styfle/cancel-workflow-action@0.12.1
      with:
        all_but_latest: true

  vllm_unit_test:
    needs: cancel_previous_workflows
    runs-on: [self-hosted]
    timeout-minutes: 90
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Kill Running Containers
      run: |
        [[ -n $(docker ps -q) ]] && docker kill $(docker ps -q) || echo "No running containers to kill."
    - name: Build And Test
      run: ./tools/run_test.sh vllm_unit_test
